### ISSUE TITLE
Customize markdown image format instead of HTML

### ISSUE THREAD

**Issue by bsplu** [TeamMeow/vscode-math-to-image#5]
I would suggest to set the default inset code block using markdown or HTML format by customization, 
because the the current HTML format may looks wired in other render engine, like Typora or Github web view.

For example, `$n_i^t$: the number of..` will be to 
`<!-- $n_i^t$ --> <img src="https://render.githubusercontent.com/render/math?math=n_i%5Et">: the number of...`. 
It looks good in vscode, but a new line will be introduced in Github web view, somewhat like
"![$n_i^t$](https://render.githubusercontent.com/render/math?math=n_i%5Et)
: the number of...". The comment `<!-- $n_i^t$ --> `can not be hidden in Typora.

The markdown image format,
`![$n_i^t$](https://render.githubusercontent.com/render/math?math=n_i%5Et): the number of...`,
 will not have this problem.

**Comment by spencerwooo** [comment]
> ```markdown
>  <img src="https://render.githubusercontent.com/render/math?math=n_i%5Et">: the number of...
> ```
> 
> It looks good in vscode, but a new line will be introduced in Github web view, somewhat like
> "![$n_i^t$](https://render.githubusercontent.com/render/math?math=n_i%5Et)
> : the number of...".

Are you sure about this? Take a look at the example folder: https://github.com/TeamMeow/vscode-math-to-image/blob/master/examples/example.md#inline-equation-2

![image](https://user-images.githubusercontent.com/32114380/103261932-41c61500-49de-11eb-8ed7-4657c612b69d.png)

which is rendered with the following text:

```markdown
### Inline equation

In physics, the mass-energy equivalence is stated by the equation <!-- $E=mc^2$ --> <img style="transform: translateY(0.1em); background: white;" src="svg/9GYiSwRTee.svg">, discovered in 1905 by Albert Einstein.
```

I don't think new lines are present here.

Primary reasons for the image tag implementation instead of markdown style `![]()` is the need for integrating optional styles. Hope you understand. Closing this for now, but feel free to further share your use cases.

**Comment by CJuette** [comment]
Hi, could this be made a selection (could be HTML-default as well)? I for one would like to keep my markdown files clean markdown, and don't add any HTML, in case I want to process them into PDFs or something using pandoc...
